version: "3"
services:
  server:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/kameleoon_test_db?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    container_name: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - springmysql-net
    environment:
      MYSQL_DATABASE: kameleoon_test_db
      MYSQL_ROOT_PASSWORD: root



networks:
  springmysql-net:





